# Análisis salarial del Rayo Vallecano

Este notebook carga el CSV y genera 10 estadísticas relevantes:
1. Jugadores que terminan contrato antes.
2. Top salarios anuales.
3. Top salarios semanales.
4. Reservas más caras.
5. Titulares más caros.
6. Masa salarial por rol.
7. Edad media por rol.
8. Jugadores con mayor compromiso económico restante.
9. Distribución salarial por posición.
10. Cláusulas de rescisión más altas.

In [2]:

import pandas as pd

df = pd.read_csv(r"rayo_vallecano_salarios.csv")
df.head()

,Jugador,Posición,Detalle,Edad,País,Salario semanal (EUR),Salario fijo anual (EUR),Bonus anual (EUR),Total anual (EUR),Fichado,Vencimiento,Años restantes,Importe restante (EUR),Cláusula rescisión (EUR),Estado,Rol
0,Augusto Batalla,K,GK,29,Argentina,40000,2080000,520000,2600000,Jul 1 2025,Jun 30 2030,5,10400000,NaN,Active,Starter
1,Florian Lejeune,D,CB,34,Francia,40000,2080000,520000,2600000,May 4 2026,Jun 30 2028,3,6240000,NaN,Active,Starter
2,Isi Palazón,F,SS,31,España,40000,2080000,520000,2600000,May 8 2023,Jun 30 2028,3,6240000,50000000.0,Active,Starter
3,Álvaro García,F,LW,33,España,40000,2080000,520000,2600000,Feb 11 2025,Jun 30 2028,3,6240000,NaN,Active,Reserve
4,Luiz Felipe,D,CB,28,Italia,40000,2080000,520000,2600000,Jul 7 2025,Jun 30 2026,1,2080000,NaN,Active,Reserve

## 1. Jugadores que terminan contrato antes

In [14]:

df.sort_values('Años restantes')[['Jugador','Vencimiento','Años restantes','Salario fijo anual (EUR)']].head(20)

             Jugador  Vencimiento  Años restantes  Salario fijo anual (EUR)
4        Luiz Felipe  Jun 30 2026               1                   2080000
15    Alfonso Espino  Jun 30 2026               1                    940000
13       Óscar Trejo  Jun 30 2026               1                   1040000
8         Unai López  Jun 30 2026               1                   1670000
23       Nobel Mendy  Jun 30 2026               1                    630000
18     Gerard Gumbau  Jun 30 2026               1                    830000
17    Ilias Akhomach  Jun 30 2026               1                    830000
16     Carlos Martín  Jun 30 2026               1                    830000
24       Abdul Mumin  Jun 30 2026               1                    520000
25  Jozhua Vertrouwd  Jun 30 2026               1                    310000
21     Dani Cárdenas  Jun 30 2027               2                    630000
19    Sergio Camello  Jun 30 2027               2                    830000
14       Iván Balliu  Jun 30 2027               2                    940000
5     Óscar Valentín  Jun 30 2027               2                   1880000
22        Pathé Ciss  Jun 30 2027               2                    630000
26      Samu Becerra  Jun 30 2027               2                    190000
2        Isi Palazón  Jun 30 2028               3                   2080000
1    Florian Lejeune  Jun 30 2028               3                   2080000
12       Randy Nteka  Jun 30 2028               3                   1250000
10        Pedro Díaz  Jun 30 2028               3                   1560000

## 2. Top 10 salarios anuales

In [16]:

df.sort_values('Total anual (EUR)', ascending=False)[['Jugador','Salario fijo anual (EUR)','Total anual (EUR)','Rol']].head(10)

           Jugador  Salario fijo anual (EUR)  Total anual (EUR)      Rol
0  Augusto Batalla                   2080000            2600000  Starter
1  Florian Lejeune                   2080000            2600000  Starter
2      Isi Palazón                   2080000            2600000  Starter
3    Álvaro García                   2080000            2600000  Reserve
4      Luiz Felipe                   2080000            2600000  Reserve
5   Óscar Valentín                   1880000            2360000  Starter
7  Jorge de Frutos                   1880000            2360000  Starter
6     Andrei Rațiu                   1880000            2300000  Starter
8       Unai López                   1670000            2090000  Reserve
9    Pep Chavarría                   1670000            2090000  Reserve

## 3. Top 10 salarios semanales

In [5]:

df.sort_values('Salario semanal (EUR)', ascending=False)[['Jugador','Salario semanal (EUR)']].head(10)

           Jugador  Salario semanal (EUR)
0  Augusto Batalla                  40000
1  Florian Lejeune                  40000
2      Isi Palazón                  40000
3    Álvaro García                  40000
4      Luiz Felipe                  40000
5   Óscar Valentín                  36154
6     Andrei Rațiu                  36154
7  Jorge de Frutos                  36154
8       Unai López                  32115
9    Pep Chavarría                  32115

## 4. Reservas más caras

In [6]:

df[df['Rol']=='Reserve'].sort_values('Total anual (EUR)', ascending=False)[['Jugador','Total anual (EUR)']].head(10)

             Jugador  Total anual (EUR)
3      Álvaro García            2600000
4        Luiz Felipe            2600000
8         Unai López            2090000
9      Pep Chavarría            2090000
10        Pedro Díaz            1960000
11  Alexandre Alemão            1840000
12       Randy Nteka            1560000
13       Óscar Trejo            1290000
14       Iván Balliu            1170000
16     Carlos Martín            1040000

## 5. Titulares más caros

In [7]:

df[df['Rol']=='Starter'].sort_values('Total anual (EUR)', ascending=False)[['Jugador','Total anual (EUR)']].head(10)

            Jugador  Total anual (EUR)
0   Augusto Batalla            2600000
1   Florian Lejeune            2600000
2       Isi Palazón            2600000
5    Óscar Valentín            2360000
7   Jorge de Frutos            2360000
6      Andrei Rațiu            2300000
15   Alfonso Espino            1170000
17   Ilias Akhomach            1040000
18    Gerard Gumbau            1040000
20       Fran Pérez             920000

## 6. Masa salarial por rol

In [8]:

df.groupby('Rol')['Total anual (EUR)'].agg(['count','sum','mean']).sort_values('sum', ascending=False)

         count       sum          mean
Rol
Reserve     16  22112000  1.382000e+06
Starter     11  19770000  1.797273e+06

## 7. Edad media por rol

In [9]:

df.groupby('Rol')['Edad'].agg(['mean','min','max'])

              mean  min  max
Rol
Reserve  27.750000   19   37
Starter  28.181818   21   34

## 8. Mayor compromiso económico restante

In [10]:

df.sort_values('Importe restante (EUR)', ascending=False)[['Jugador','Importe restante (EUR)','Años restantes']].head(10)

             Jugador  Importe restante (EUR)  Años restantes
0    Augusto Batalla                10400000               5
6       Andrei Rațiu                 9400000               5
9      Pep Chavarría                 8350000               5
11  Alexandre Alemão                 7300000               5
2        Isi Palazón                 6240000               3
3      Álvaro García                 6240000               3
1    Florian Lejeune                 6240000               3
7    Jorge de Frutos                 5640000               3
10        Pedro Díaz                 4680000               3
5     Óscar Valentín                 3760000               2

## 9. Salario medio por posición

In [11]:

df.groupby('Posición')['Total anual (EUR)'].mean().sort_values(ascending=False)

Posición
K    1.690000e+06
F    1.629000e+06
D    1.527778e+06
M    1.410333e+06
Name: Total anual (EUR), dtype: float64

## 10. Cláusulas de rescisión más altas

In [12]:

df[['Jugador','Cláusula rescisión (EUR)']].dropna().sort_values('Cláusula rescisión (EUR)', ascending=False).head(10)

       Jugador  Cláusula rescisión (EUR)
2  Isi Palazón                50000000.0